version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        container_name: php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:  
        image: mysql:8
        container_name: mysql
        secrets:
            - "mysql_pwd"
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_pwd

    adminer:
        build: ./adminer
        container_name: adminer
        restart: always
        ports:
           - "6080:8080"

secrets: 
    mysql_pwd:
      file: ./hosts/mysql_pwd 
